// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDC-xsf4Reodmwkt7IvEGJLQOD3bnm6H0',
    appId: '1:882033544453:web:e24890c84db7659b2c3b6c',
    messagingSenderId: '882033544453',
    projectId: 'instagramclone-61e6d',
    authDomain: 'instagramclone-61e6d.firebaseapp.com',
    storageBucket: 'instagramclone-61e6d.appspot.com',
    measurementId: 'G-GQREH29C4Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAps16zwn6kzTL8iCBGF03L6K7Yn9ub7Tk',
    appId: '1:882033544453:android:500c51d191a9025e2c3b6c',
    messagingSenderId: '882033544453',
    projectId: 'instagramclone-61e6d',
    storageBucket: 'instagramclone-61e6d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdb6kcCZAakUq2KuyMKMK6WXdUSnM8lHk',
    appId: '1:882033544453:ios:a839dbd3fe8d56532c3b6c',
    messagingSenderId: '882033544453',
    projectId: 'instagramclone-61e6d',
    storageBucket: 'instagramclone-61e6d.appspot.com',
    iosBundleId: 'com.example.instagramclone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdb6kcCZAakUq2KuyMKMK6WXdUSnM8lHk',
    appId: '1:882033544453:ios:db47176966e9634d2c3b6c',
    messagingSenderId: '882033544453',
    projectId: 'instagramclone-61e6d',
    storageBucket: 'instagramclone-61e6d.appspot.com',
    iosBundleId: 'com.example.instagramclone.RunnerTests',
  );
}
